---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
## Eine Skala ersetzen - Achsen (Datum)

```{r, echo=FALSE}

letzter_monat <- Sys.Date() - 0:29
temp_vek <- runif(n = 30, min = -10, max = 10)

tib <- tibble(
  datum = letzter_monat,
  temperatur = temp_vek
)


```

```{r}

tibble::tribble(
  ~Code,                                 ~Meaning,
  "%S",                         "second (00-59)",
  "%M",                         "minute (00-59)",
  "%l",          "hour, in 12-hour clock (1-12)",
  "%I",         "hour, in 12-hour clock (01-12)",
  "%H",         "hour, in 24-hour clock (01-24)",
  "%a", "day of the week, abbreviated (Mon-Sun)",
  "%A",  "day of the week, full (Monday-Sunday)",
  "%e",                "day of the month (1-31)",
  "%d",               "day of the month (01-31)",
  "%m",                 "month, numeric (01-12)",
  "%b",           "month, abbreviated (Jan-Dec)",
  "%B",         "month, full (January-December)",
  "%y",          "year, without century (00-99)",
  "%Y",         "year, with century (0000-9999)"
) %>% 
  gt::gt() %>% 
  gt::opt_row_striping() %>% 
  gt::tab_options(column_labels.font.weight = "bold")

```

---

pull.left[

```{r, eval = FALSE, echo = TRUE}

ggplot(data = tib,
       mapping =  aes(x = datum, 
                      y = temperatur)) +
  geom_line() + 
  coord_flip() + 
  scale_x_date(
    date_labels = "%a, %b %d, %Y",  #<<
    date_breaks = "1 day") + #<<
  theme_minimal() +
  theme(panel.grid.minor.y = element_blank())

```

]

.footnote[
From:[ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/scale-position.html#date-scales)
]
